CREATE TABLESPACE ASIGNACION
DATAFILE 'C:\app\Alejandro\product\21c\oradata\XE\ASIGNACION.DBF'
SIZE 100M
AUTOEXTEND ON NEXT 250K
MAXSIZE 200M;

CREATE TABLE HEADQUARTERS(
	ID_HEADQUARTER NUMBER DEFAULT ID_INCREMENT_HEADQUARTERS.NEXTVAL,
	HEADQUARTER_CITY VARCHAR2(50),
	CONSTRAINT PK_HEADQUARTERS PRIMARY KEY (ID_HEADQUARTER)
);

CREATE TABLE CAREERS(
	ID_CAREER NUMBER DEFAULT ID_INCREMENT_CAREERS.NEXTVAL,
	CAREER_NAME VARCHAR2(50),
	CONSTRAINT PK_CAREERS PRIMARY KEY (ID_CAREER)
);

CREATE TABLE HEADQUARTERS_CAREERS(
	ID_HEADQUARTER_CAREER NUMBER DEFAULT ID_INCREMENT_HC.NEXTVAL,
	ID_HEADQUARTER NUMBER,
	ID_CAREER NUMBER,
	CONSTRAINT PK_HEADQUARTERS_CAREERS PRIMARY KEY (ID_HEADQUARTER_CAREER),
	CONSTRAINT FK_HEADQUARTER FOREIGN KEY(ID_HEADQUARTER) REFERENCES HEADQUARTERS(ID_HEADQUARTER),
	CONSTRAINT FK_CAREER FOREIGN KEY(ID_CAREER) REFERENCES CAREERS(ID_CAREER)
);

CREATE TABLE EDUCATION_TYPES(
	ID_EDUCATION_TYPE NUMBER DEFAULT ID_INCREMENT_ET.NEXTVAL,
	EDUCATION_TYPE_NAME VARCHAR2(20),
	CONSTRAINT PK_EDUCATION_TYPES PRIMARY KEY (ID_EDUCATION_TYPE)
);

CREATE TABLE SELECTION_PROCESSES(
	ID_PROCESS NUMBER DEFAULT ID_INCREMENT_SELECTION_PROCESSES.NEXTVAL,
	PROCESS_DATE VARCHAR2(100),
	CONSTRAINT PK_SELECTION_PROCESSES PRIMARY KEY (ID_PROCESS)
);

CREATE TABLE CANDIDATES(
	ID_CANDIDATE VARCHAR2(11),
	NAME VARCHAR2(50),
	LASTNAME VARCHAR2(50),
	ID_TYPE VARCHAR2(10),
	SEX VARCHAR2(15),
	CITY VARCHAR2(50),
	ESTATE VARCHAR2(50),
	ICFES_GENERAL NUMBER,
	AGE INTEGER,
	ID_HEADQUARTER_CAREER NUMBER,
	ID_EDUCATION NUMBER,
	CONSTRAINT PK_CANDIDATES PRIMARY KEY (ID_CANDIDATE),
	CONSTRAINT FK_HEADQUARTER_CAREER FOREIGN KEY(ID_HEADQUARTER_CAREER) REFERENCES HEADQUARTERS_CAREERS(ID_HEADQUARTER_CAREER),
	CONSTRAINT FK_EDUCATION_TYPE FOREIGN KEY(ID_EDUCATION) REFERENCES EDUCATION_TYPES(ID_EDUCATION_TYPE)
);

CREATE TABLE SELECTIONS(
	ID_SELECTION NUMBER DEFAULT ID_INCREMENT_SELECTIONS.NEXTVAL,
	ID_CANDIDATE VARCHAR2(11),
	ID_SELECTION_PROCESS NUMBER,
	PERCENTAGE NUMBER,
	PRIORITY NUMBER,
	CONSTRAINT PK_SELECTION PRIMARY KEY (ID_SELECTION),
	CONSTRAINT FK_CANDIDATE FOREIGN KEY(ID_CANDIDATE) REFERENCES CANDIDATES(ID_CANDIDATE),
	CONSTRAINT FK_SELECTION_PROCESS FOREIGN KEY(ID_SELECTION_PROCESS) REFERENCES SELECTION_PROCESSES(ID_PROCESS)
)
PARTITION BY LIST (ID_SELECTION_PROCESS)(
	PARTITION p_initial_partition VALUES (-1)
);

CREATE TABLE CRITERIA(
	ID_CRITERION VARCHAR2(10),
	CATEGORY VARCHAR2(50),
	NAME VARCHAR2(50),
	COLUMN_NAME VARCHAR2(30),
	TABLE_NAME VARCHAR2(30),
	STATISTIC_TYPE VARCHAR2(15),
	VALUE VARCHAR2(100),
	SCHEDULED_VALUE VARCHAR2(100),
	MANDATORY CHAR(1) CHECK (MANDATORY IN ('1', '0')),
	CONSTRAINT PK_CRITERIA PRIMARY KEY(ID_CRITERION)
);

CREATE TABLE CRITERIA_CONFIGURATION(
	ID_CONF NUMBER DEFAULT criteria_configuration_seq.NEXTVAL,
	ID_CRITERION VARCHAR2(10),
	VALUE VARCHAR2(50),
	PRIORITY VARCHAR2(10),
	PERCENTAGE NUMBER,
	COMPARATOR VARCHAR2(30),
	AUTOMATIZED NUMBER CHECK (AUTOMATIZED IN (1, 0)),
	CONSTRAINT PK_CONF PRIMARY KEY(ID_CONF),
	CONSTRAINT FK_CRITERIA FOREIGN KEY(ID_CRITERION) REFERENCES CRITERIA(ID_CRITERION)
);

CREATE OR REPLACE TYPE SELECTIONS_RECORD AS OBJECT (
    ID_SELECTION NUMBER,
    ID_CANDIDATE VARCHAR2(11),
    ID_SELECTION_PROCESS NUMBER,
    PERCENTAGE NUMBER,
    PRIORITY NUMBER
);

CREATE OR REPLACE TYPE SelectionsTableType AS TABLE OF SELECTIONS_RECORD;
