CREATE TABLESPACE ASIGNACION
DATAFILE 'C:\app\Alejandro\product\21c\oradata\XE\ASIGNACION.DBF'
SIZE 100M
AUTOEXTEND ON NEXT 250K
MAXSIZE 200M;

CREATE SEQUENCE ID_INCREMENT_HEADQUARTERS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_CAREERS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_ET
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_HC
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE HEADQUARTERS(
	ID_HEADQUARTER NUMBER DEFAULT ID_INCREMENT_HEADQUARTERS.NEXTVAL,
	HEADQUARTER_CITY VARCHAR2(50),
	--HEADQUARTER_ESTATE VARCHAR2(50),
	CONSTRAINT PK_HEADQUARTERS PRIMARY KEY (ID_HEADQUARTER)
);

--ALTER TABLE CAREERS 
--DROP COLUMN FACULTY_NAME;

CREATE INDEX IDX_CITY_HEADQUARTERS
ON HEADQUARTERS(HEADQUARTER_CITY);

CREATE INDEX IDX_ESTATE_HEADQUARTERS
ON HEADQUARTERS(HEADQUARTER_ESTATE);

SELECT index_name, index_type, uniqueness
FROM user_indexes;

CREATE TABLE CAREERS(
	ID_CAREER NUMBER DEFAULT ID_INCREMENT_CAREERS.NEXTVAL,
	CAREER_NAME VARCHAR2(50),
	--FACULTY_NAME VARCHAR2(50),
	CONSTRAINT PK_CAREERS PRIMARY KEY (ID_CAREER)
);

CREATE INDEX IDX_NAME_CAREERS
ON CAREERS(CAREER_NAME);

CREATE INDEX IDX_FACULTY_NAME_CAREERS
ON CAREERS(FACULTY_NAME);

CREATE TABLE HEADQUARTERS_CAREERS(
	ID_HEADQUARTER_CAREER NUMBER DEFAULT ID_INCREMENT_HC.NEXTVAL,
	ID_HEADQUARTER NUMBER,
	ID_CAREER NUMBER,
	CONSTRAINT PK_HEADQUARTERS_CAREERS PRIMARY KEY (ID_HEADQUARTER_CAREER),
	CONSTRAINT FK_HEADQUARTER FOREIGN KEY(ID_HEADQUARTER) REFERENCES HEADQUARTERS(ID_HEADQUARTER),
	CONSTRAINT FK_CAREER FOREIGN KEY(ID_CAREER) REFERENCES CAREERS(ID_CAREER)
);



CREATE TABLE EDUCATION_TYPES(
	ID_EDUCATION_TYPE NUMBER DEFAULT ID_INCREMENT_ET.NEXTVAL,
	EDUCATION_TYPE_NAME VARCHAR2(20),
	CONSTRAINT PK_EDUCATION_TYPES PRIMARY KEY (ID_EDUCATION_TYPE)
);

CREATE TABLE SELECTION_PROCESSES(
	ID_PROCESS VARCHAR2(10),
	PROCESS_DATE TIMESTAMP,
	CONSTRAINT PK_SELECTION_PROCESSES PRIMARY KEY (ID_PROCESS)
);

CREATE TABLE CANDIDATES(
	ID_CANDIDATE VARCHAR2(11),
	NAME VARCHAR2(50),
	LASTNAME VARCHAR2(50),
	ID_TYPE VARCHAR2(10),
	SEX VARCHAR2(15),
	CITY VARCHAR2(50),
	ESTATE VARCHAR2(50),
	ICFES_GENERAL NUMBER,
	AGE INTEGER,
	ID_HEADQUARTER_CAREER NUMBER,
	ID_EDUCATION NUMBER,
	CONSTRAINT PK_CANDIDATES PRIMARY KEY (ID_CANDIDATE),
	CONSTRAINT FK_HEADQUARTER_CAREER FOREIGN KEY(ID_HEADQUARTER_CAREER) REFERENCES HEADQUARTERS_CAREERS(ID_HEADQUARTER_CAREER),
	CONSTRAINT FK_EDUCATION_TYPE FOREIGN KEY(ID_EDUCATION) REFERENCES EDUCATION_TYPES(ID_EDUCATION_TYPE)
);

--ALTER TABLE CANDIDATES MODIFY ID_CANDIDATE VARCHAR2(11);

CREATE INDEX IDX_CITY_CANDIDATE
ON CANDIDATES(CITY);

CREATE INDEX IDX_ESTATE_CANDIDATE
ON CANDIDATES(ESTATE);

CREATE TABLE SELECTIONS(
	ID_SELECTION VARCHAR(10),
	ID_CANDIDATE VARCHAR2(10),
	ID_SELECTION_PROCESS VARCHAR2(10),
	PERCENTAGE NUMBER,
	CONSTRAINT PK_SELECTION PRIMARY KEY (ID_SELECTION),
	CONSTRAINT FK_CANDIDATE FOREIGN KEY(ID_CANDIDATE) REFERENCES CANDIDATES(ID_CANDIDATE),
	CONSTRAINT FK_SELECTION_PROCESS FOREIGN KEY(ID_SELECTION_PROCESS) REFERENCES SELECTION_PROCESSES(ID_PROCESS)
);

CREATE TABLE CRITERIA(
	ID_CRITERION VARCHAR2(10),
	CATEGORY VARCHAR2(50),
	NAME VARCHAR2(50),
	COLUMN_NAME VARCHAR2(30),
	TABLE_NAME VARCHAR2(30),
	STATISTIC_TYPE VARCHAR2(15),
	VALUE VARCHAR2(100),
	MANDATORY CHAR(1) CHECK (MANDATORY IN ('1', '0'))
);


