
--SELECT * FROM all_tables;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER APP_ASIG_ESTUDIANTES IDENTIFIED BY 1007707024;

ALTER USER APP_ASIG_ESTUDIANTES QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO APP_ASIG_ESTUDIANTES;

GRANT CREATE ANY TABLE TO APP_ASIG_ESTUDIANTES;

GRANT CREATE ANY PROCEDURE TO APP_ASIG_ESTUDIANTES;

GRANT CREATE ANY VIEW TO APP_ASIG_ESTUDIANTES;

GRANT CREATE TABLESPACE TO APP_ASIG_ESTUDIANTES;

ALTER USER APP_ASIG_ESTUDIANTES DEFAULT TABLESPACE ASIGNACION;
GRANT UNLIMITED TABLESPACE TO APP_ASIG_ESTUDIANTES;