
SELECT * FROM all_tables;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER APP_ASIG_ESTUDIANTES IDENTIFIED BY 1007707024;

ALTER USER APP_ASIG_ESTUDIANTES QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO APP_ASIG_ESTUDIANTES;

GRANT CREATE ANY TABLE TO APP_ASIG_ESTUDIANTES;

GRANT CREATE ANY PROCEDURE TO APP_ASIG_ESTUDIANTES;

GRANT CREATE ANY VIEW TO APP_ASIG_ESTUDIANTES;

GRANT CREATE TABLESPACE TO APP_ASIG_ESTUDIANTES;

SELECT *
FROM DBA_TABLESPACES
WHERE tablespace_name = 'ASIGNACION';

DROP TABLESPACE APP_ASIG_ESTUDIANTES;

CREATE TABLESPACE ASIGNACION
DATAFILE 'C:\app\Alejandro\product\21c\oradata\XE\ASIGNACION.DBF'
SIZE 100M
AUTOEXTEND ON NEXT 250K
MAXSIZE 200M;

ALTER USER APP_ASIG_ESTUDIANTES DEFAULT TABLESPACE ASIGNACION;

SELECT table_name, tablespace_name
FROM DBA_TABLES
WHERE owner = 'APP_ASIG_ESTUDIANTES' AND table_name = 'HEADQUARTERS';

ALTER USER APP_ASIG_ESTUDIANTES DEFAULT TABLESPACE ASIGNACION;
GRANT UNLIMITED TABLESPACE TO APP_ASIG_ESTUDIANTES;



