CREATE SEQUENCE ID_INCREMENT_HEADQUARTERS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_CAREERS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_ET
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_HC
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_SELECTION_PROCESSES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ID_INCREMENT_SELECTIONS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE criteria_configuration_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;